//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout
    {
        public workout()
        {
            this.tasks = new HashSet<task>();
        }
    
        public string taskName { get; set; }
        public string workoutName { get; set; }
    
        public virtual ICollection<task> tasks { get; set; }
        public virtual workout1 workout1 { get; set; }
    }
}
