//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout1
    {
        public workout1()
        {
            this.workouts = new HashSet<workout>();
        }
    
        public string workoutName { get; set; }
        public string userName { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<workout> workouts { get; set; }
    }
}
